# Generated by Django 3.1.6 on 2021-12-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='last_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='second_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Segundo nombre'),
        ),
    ]
