# Generated by Django 3.1.6 on 2021-12-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20211229_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='last_name',
            field=models.CharField(default='', max_length=80, verbose_name='Primer apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guests',
            name='sec_last_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Segundo apellido'),
        ),
    ]
