# Generated by Django 3.1.6 on 2022-01-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20211229_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('artist', models.CharField(max_length=255, verbose_name='Artista')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/songs', verbose_name='Imagen')),
                ('song_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de la cancion')),
                ('duration', models.CharField(max_length=255, verbose_name='Duración')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
    ]
